Hallo,

die folgenden Hintergrundjobs sind seit [% SELF.start_time.to_kivitendo %] [% SELF.start_time.to_kivitendo_time %] ausgeführt worden und schlugen fehl:

[%- FOREACH entry = SELF.entries %]
Paketname:     [% entry.package_name %]
Ausgeführt um: [% entry.run_at.to_kivitendo %] [% entry.run_at.to_kivitendo_time %]
Fehler:        [% entry.error_col %]
[% UNLESS loop.last %]============================================================[% END %]
[%- END %]
Gruß,
kivitendo
